obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
obj-$(CONFIG_TCPC_RT1711H)	+= rt-charger.o
obj-$(CONFIG_CHARGER_PCA9468)	+= pca9468_charger.o
