cp ./net/bridge/br_netfilter.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/ec_hid_driver/ec_i2c_interface.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/ec_hid_driver/ec_i2c_updatefw.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/aura_sync/ene_6k582_station.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/dt_aura/ene_8k41_dt.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/dt_power/ene_8k41_power.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/usb/host/ghci/ghci-hcd.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/media/usb/gspca/gspca_main.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/usb/host/ghci/gxhci-hcd.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/aura_sync/ml51fb9ae_inbox.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/media/platform/msm/dvb/adapter/mpq-adapter.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/media/platform/msm/dvb/demux/mpq-dmx-hw-plugin.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/platform/msm/msm_11ad/msm_11ad_proxy.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/media/rc/msm-geni-ir.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/fan/nct7802.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/char/rdbg.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./techpack/data/rmnet/perf/rmnet_perf.ko  /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./techpack/data/rmnet/shs/rmnet_shs.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/input/touchscreen/station_goodix_gtx8/station_goodix_touch.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/ec_hid_driver/station_key.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/media/platform/msm/broadcast/tspp.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
cp ./drivers/net/wireless/ath/wil6210/wil6210.ko /data/imran/Kirisakura/AnyKernel3/modules/system/vendor/lib/modules/
